# DO NOT EDIT THIS FILE
# DO NOT EDIT THIS FILE
# DO NOT EDIT THIS FILE
# DO NOT EDIT THIS FILE
# Generated code
# DO NOT EDIT THIS FILE
# DO NOT EDIT THIS FILE
# DO NOT EDIT THIS FILE
# DO NOT EDIT THIS FILE

# Auto-detect the directory where makefiles are located
MAKEFILES_DIR ?= $(dir $(lastword $(MAKEFILE_LIST)))
MAKEFILES_DIR := $(patsubst %/,%,$(MAKEFILES_DIR))

# This file maintains backwards compatibility by including both common and legacy modules
# It also provides smart detection to use bake module when docker-bake.hcl exists

# Include common functionality
-include $(MAKEFILES_DIR)/Makefile.docker-common.mk

# Check if docker-bake.hcl exists
HAS_BAKE_FILE := $(shell test -f docker-bake.hcl && echo "YES" || echo "NO")

# Include appropriate module based on project type
ifeq ($(HAS_BAKE_FILE),YES)
  # Project has docker-bake.hcl, include bake module
  -include $(MAKEFILES_DIR)/Makefile.docker-bake.mk
  
  # Smart aliases that detect bake usage
  docker-build: docker-bake-build ## Build Docker images (auto-detects bake)
  docker-push: docker-bake-push ## Push Docker images (auto-detects bake)
  docker-load: docker-bake-load ## Load Docker images locally (auto-detects bake)
  
  docker-print: docker-bake-print ## Print configuration (bake mode)
  docker-targets: docker-bake-targets ## List available targets (bake mode)
  
else
  # Traditional single Dockerfile project, include legacy module
  -include $(MAKEFILES_DIR)/Makefile.docker-legacy.mk
endif

# Common targets that work for both
.PHONY: docker-build docker-push docker-load docker-print docker-targets