# DO NOT EDIT THIS FILE
# DO NOT EDIT THIS FILE
# DO NOT EDIT THIS FILE
# DO NOT EDIT THIS FILE
# Generated code
# DO NOT EDIT THIS FILE
# DO NOT EDIT THIS FILE
# DO NOT EDIT THIS FILE
# DO NOT EDIT THIS FILE

# Rust configuration
RUST_TOOLCHAIN ?= stable
RUST_TARGETS ?= x86_64-unknown-linux-gnu
RUST_FEATURES ?= --all-features
RUST_WORKSPACE ?= .

# Cargo commands
CARGO_CMD = cargo
CARGO_BUILD = $(CARGO_CMD) build
CARGO_TEST = $(CARGO_CMD) test
CARGO_CHECK = $(CARGO_CMD) check
CARGO_CLIPPY = $(CARGO_CMD) clippy
CARGO_FMT = $(CARGO_CMD) fmt
CARGO_AUDIT = $(CARGO_CMD) audit
CARGO_TARPAULIN = $(CARGO_CMD) tarpaulin

# Coverage configuration
COVERAGE_THRESHOLD ?= 80
COVERAGE_OUTPUT_DIR ?= target/coverage
COVERAGE_FORMAT ?= xml

# Build configuration
BUILD_MODE ?= release
BUILD_TARGET_DIR ?= target
RUST_LOG ?= info

# Test configuration
TEST_THREADS ?= $(shell nproc 2>/dev/null || echo 1)

## Rust
rust-check: ## Check Rust code without building
	@echo "$(GREEN)Checking Rust code...$(RESET)"
	@cd $(RUST_WORKSPACE) && $(CARGO_CHECK) $(RUST_FEATURES)

rust-build: ## Build Rust project
	@echo "$(GREEN)Building Rust project...$(RESET)"
	@cd $(RUST_WORKSPACE) && $(CARGO_BUILD) $(RUST_FEATURES) \
		$(if $(filter release,$(BUILD_MODE)),--release,)

rust-build-all-targets: ## Build for all configured targets
	@echo "$(GREEN)Building for all targets...$(RESET)"
	@for target in $(RUST_TARGETS); do \
		echo "Building for $$target..."; \
		cd $(RUST_WORKSPACE) && $(CARGO_BUILD) $(RUST_FEATURES) --target $$target \
			$(if $(filter release,$(BUILD_MODE)),--release,); \
	done

rust-test: ## Run Rust tests
	@echo "$(GREEN)Running Rust tests...$(RESET)"
	@cd $(RUST_WORKSPACE) && RUST_LOG=$(RUST_LOG) $(CARGO_TEST) $(RUST_FEATURES) \
		-- --test-threads=$(TEST_THREADS)

rust-test-ignored: ## Run ignored tests
	@echo "$(GREEN)Running ignored tests...$(RESET)"
	@cd $(RUST_WORKSPACE) && $(CARGO_TEST) $(RUST_FEATURES) -- --ignored

rust-test-all: rust-test rust-test-ignored ## Run all tests including ignored ones

rust-bench: ## Run Rust benchmarks
	@echo "$(GREEN)Running benchmarks...$(RESET)"
	@cd $(RUST_WORKSPACE) && $(CARGO_TEST) $(RUST_FEATURES) --benches

rust-doc: ## Generate Rust documentation
	@echo "$(GREEN)Generating documentation...$(RESET)"
	@cd $(RUST_WORKSPACE) && $(CARGO_CMD) doc $(RUST_FEATURES) --no-deps

rust-doc-open: ## Generate and open documentation
	@echo "$(GREEN)Generating and opening documentation...$(RESET)"
	@cd $(RUST_WORKSPACE) && $(CARGO_CMD) doc $(RUST_FEATURES) --no-deps --open

## Linting and Formatting
rust-fmt: ## Format Rust code
	@echo "$(GREEN)Formatting Rust code...$(RESET)"
	@cd $(RUST_WORKSPACE) && $(CARGO_FMT) --all

rust-fmt-check: ## Check Rust code formatting
	@echo "$(GREEN)Checking Rust code formatting...$(RESET)"
	@cd $(RUST_WORKSPACE) && $(CARGO_FMT) --all -- --check

rust-clippy: ## Run Clippy linter
	@echo "$(GREEN)Running Clippy...$(RESET)"
	@cd $(RUST_WORKSPACE) && $(CARGO_CLIPPY) $(RUST_FEATURES) --all-targets -- -D warnings

rust-clippy-fix: ## Run Clippy with automatic fixes
	@echo "$(GREEN)Running Clippy with fixes...$(RESET)"
	@cd $(RUST_WORKSPACE) && $(CARGO_CLIPPY) $(RUST_FEATURES) --all-targets --fix

rust-lint: rust-fmt-check rust-clippy ## Run all linting checks

## Security
rust-audit: ## Run security audit
	@echo "$(GREEN)Running security audit...$(RESET)"
	@cd $(RUST_WORKSPACE) && $(CARGO_AUDIT)

rust-audit-fix: ## Run security audit with fixes
	@echo "$(GREEN)Running security audit with fixes...$(RESET)"
	@cd $(RUST_WORKSPACE) && $(CARGO_AUDIT) fix

## Coverage
rust-coverage: ## Generate test coverage
	@echo "$(GREEN)Generating test coverage...$(RESET)"
	@mkdir -p $(COVERAGE_OUTPUT_DIR)
	@cd $(RUST_WORKSPACE) && $(CARGO_TARPAULIN) $(RUST_FEATURES) \
		--out $(COVERAGE_FORMAT) \
		--output-dir $(COVERAGE_OUTPUT_DIR) \
		--timeout 300

rust-coverage-html: ## Generate HTML coverage report
	@echo "$(GREEN)Generating HTML coverage report...$(RESET)"
	@mkdir -p $(COVERAGE_OUTPUT_DIR)
	@cd $(RUST_WORKSPACE) && $(CARGO_TARPAULIN) $(RUST_FEATURES) \
		--out Html \
		--output-dir $(COVERAGE_OUTPUT_DIR) \
		--timeout 300

rust-coverage-check: rust-coverage ## Check coverage threshold
	@echo "$(GREEN)Checking coverage threshold ($(COVERAGE_THRESHOLD)%)...$(RESET)"
	@cd $(RUST_WORKSPACE) && \
		COVERAGE=$$($(CARGO_TARPAULIN) $(RUST_FEATURES) --print-summary | grep -o '[0-9.]*%' | head -1 | tr -d '%'); \
		echo "Current coverage: $${COVERAGE}%"; \
		if [ "$$(echo "$${COVERAGE} < $(COVERAGE_THRESHOLD)" | bc -l)" = "1" ]; then \
			echo "$(YELLOW)Warning: Coverage $${COVERAGE}% is below threshold $(COVERAGE_THRESHOLD)%$(RESET)"; \
			exit 1; \
		else \
			echo "$(GREEN)Coverage $${COVERAGE}% meets threshold $(COVERAGE_THRESHOLD)%$(RESET)"; \
		fi

## Dependencies
rust-update: ## Update Rust dependencies
	@echo "$(GREEN)Updating dependencies...$(RESET)"
	@cd $(RUST_WORKSPACE) && $(CARGO_CMD) update

rust-tree: ## Show dependency tree
	@echo "$(GREEN)Showing dependency tree...$(RESET)"
	@cd $(RUST_WORKSPACE) && $(CARGO_CMD) tree

rust-outdated: ## Check for outdated dependencies
	@echo "$(GREEN)Checking for outdated dependencies...$(RESET)"
	@cd $(RUST_WORKSPACE) && $(CARGO_CMD) outdated

## Toolchain Management
rust-toolchain-install: ## Install Rust toolchain
	@echo "$(GREEN)Installing Rust toolchain $(RUST_TOOLCHAIN)...$(RESET)"
	@rustup toolchain install $(RUST_TOOLCHAIN)
	@rustup component add rustfmt clippy

rust-toolchain-update: ## Update Rust toolchain
	@echo "$(GREEN)Updating Rust toolchain...$(RESET)"
	@rustup update

rust-targets-add: ## Add compilation targets
	@echo "$(GREEN)Adding compilation targets...$(RESET)"
	@for target in $(RUST_TARGETS); do \
		echo "Adding target $$target..."; \
		rustup target add $$target; \
	done

## Tool Installation
rust-install-tools: ## Install common Rust development tools
	@echo "$(GREEN)Installing Rust development tools...$(RESET)"
	@$(CARGO_CMD) install cargo-tarpaulin cargo-audit cargo-outdated cargo-tree

## Cleaning
rust-clean: ## Clean Rust build artifacts
	@echo "$(GREEN)Cleaning build artifacts...$(RESET)"
	@cd $(RUST_WORKSPACE) && $(CARGO_CMD) clean

rust-clean-coverage: ## Clean coverage artifacts
	@echo "$(GREEN)Cleaning coverage artifacts...$(RESET)"
	@rm -rf $(COVERAGE_OUTPUT_DIR)

rust-clean-all: rust-clean rust-clean-coverage ## Clean all artifacts

## Combined Commands
rust-ci: rust-fmt-check rust-clippy rust-test rust-audit ## Run all CI checks
rust-all: rust-build rust-test rust-lint rust-coverage ## Run full development workflow

.PHONY: rust-check rust-build rust-build-all-targets rust-test rust-test-ignored rust-test-all \
        rust-bench rust-doc rust-doc-open rust-fmt rust-fmt-check rust-clippy rust-clippy-fix \
        rust-lint rust-audit rust-audit-fix rust-coverage rust-coverage-html rust-coverage-check \
        rust-update rust-tree rust-outdated rust-toolchain-install rust-toolchain-update \
        rust-targets-add rust-install-tools rust-clean rust-clean-coverage rust-clean-all \
        rust-ci rust-all