# DO NOT EDIT THIS FILE
# DO NOT EDIT THIS FILE
# DO NOT EDIT THIS FILE
# DO NOT EDIT THIS FILE
# Generated code
# DO NOT EDIT THIS FILE
# DO NOT EDIT THIS FILE
# DO NOT EDIT THIS FILE
# DO NOT EDIT THIS FILE

# Common Docker functionality shared by legacy and bake modules

# Auto-detect the directory where makefiles are located
MAKEFILES_DIR ?= $(dir $(lastword $(MAKEFILE_LIST)))
MAKEFILES_DIR := $(patsubst %/,%,$(MAKEFILES_DIR))

# Remote BuildKit settings
REMOTE_BUILD_KIT ?= tcp://buildkit.zondax.dev:8372
REMOTE_BUILD_KIT_NAME ?= zondax-builder

# Platform settings
PLATFORMS ?= linux/amd64,linux/arm64

# Build settings
DOCKER_BUILD_PROGRESS ?= auto

# Git commit hash of the current HEAD, fallback to empty string
GIT_HASH ?= $(shell git rev-parse HEAD 2>/dev/null || echo "")

# Git commit hash of the current HEAD, fallback to empty string
GIT_HASH_SHORT ?= $(shell git rev-parse --short HEAD 2>/dev/null || echo "")

# Prioritize GitHub environment variable, fallback to local git branch
# Sanitizes to valid Docker tag characters and collapses consecutive invalid chars
GIT_BRANCH ?= $(shell \
	RAW_BRANCH=""; \
	if [ -n "$$GIT_BRANCH_GITHUB" ]; then \
		RAW_BRANCH="$$GIT_BRANCH_GITHUB"; \
	else \
		RAW_BRANCH=$$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo ""); \
	fi; \
	echo "$${RAW_BRANCH}" | sed -E 's/[^a-zA-Z0-9._-]+/-/g; s/^-+//; s/-+$$//' \
)

# Get and sanitize tags pointing to HEAD, handling multiple tags
GIT_TAGS ?= $(shell \
	TAGS=$$(git tag --points-at HEAD 2>/dev/null || echo ""); \
	echo "$$TAGS" | tr ' ' '\n' | sed -E 's/[^a-zA-Z0-9._-]+/-/g; s/^-+//; s/-+$$//' | paste -sd " " - \
)

# Appends "-dirty" if there are uncommitted changes
# Empty if working directory is clean or git not available
GIT_DIRTY ?= $(shell git diff --quiet 2>/dev/null || echo "-dirty")

# Build timestamp in format YYYYMMDDHHMMSS
BUILD_DATE ?= $(shell date +%Y%m%d%H%M%S)

# Directory for build information
INFO_TMP_DIR ?= .build

# File for build information
INFO_TMP ?= $(INFO_TMP_DIR)/.env

# First build list of image tags without repository prefix
IMAGE_TAGS = \
	$(BUILD_DATE)

# Add full Git hash tag with dirty flag if needed
ifneq ($(GIT_HASH),)
IMAGE_TAGS += $(GIT_HASH)$(GIT_DIRTY)
endif

# Add short Git hash tag with dirty flag if needed
ifneq ($(GIT_HASH_SHORT),)
IMAGE_TAGS += $(GIT_HASH_SHORT)$(GIT_DIRTY)
endif

# Add branch tag if exists
ifneq ($(GIT_BRANCH),)
IMAGE_TAGS += $(GIT_BRANCH)
endif

# Add Git tags if they exist
ifneq ($(GIT_TAGS),)
IMAGE_TAGS += $(GIT_TAGS)
endif

# Helper for space substitution in tags
empty :=
space := $(empty) $(empty)

# Common setup function for remote builder
define docker_setup_builder
	@if [ -n "$(REMOTE_BUILD_KIT)" ]; then \
		docker buildx rm $(REMOTE_BUILD_KIT_NAME) > /dev/null 2>&1 || true; \
		docker buildx create \
			--driver remote \
			--name $(REMOTE_BUILD_KIT_NAME) \
			$(REMOTE_BUILD_KIT) > /dev/null 2>&1; \
	fi
endef

# Generate build information file
docker-gen-info: ## Generate build information file
	@mkdir -p $(INFO_TMP_DIR)
	@echo "GIT_HASH=$(GIT_HASH)" > $(INFO_TMP)
	@echo "GIT_HASH_SHORT=$(GIT_HASH_SHORT)" >> $(INFO_TMP)
	@echo "GIT_BRANCH=$(GIT_BRANCH)" >> $(INFO_TMP)
	@echo "GIT_TAGS=$(GIT_TAGS)" >> $(INFO_TMP)
	@echo "GIT_DIRTY=$(GIT_DIRTY)" >> $(INFO_TMP)
	@echo "BUILD_DATE=$(BUILD_DATE)" >> $(INFO_TMP)
	@echo "PLATFORMS=$(PLATFORMS)" >> $(INFO_TMP)
	@echo "IMAGE_TAGS=$(IMAGE_TAGS)" >> $(INFO_TMP)

# Display build information
docker-info: docker-gen-info ## Show build info and tags
	@cat $(INFO_TMP) || echo "Error: Could not read $(INFO_TMP)"
	@echo
	@echo "🎯 Platforms"
	@echo "$(PLATFORMS)"
	@echo
	@echo "🏷️  Image tags available:"
	@for tag in $(IMAGE_TAGS); do echo "  - $$tag"; done
	@rm -rf $(INFO_TMP_DIR)

# Install and configure Docker buildx remote builder
docker-install: docker-gen-info ## Configure buildx builder
	$(call docker_setup_builder)

# Inspect Docker buildx builder configuration
docker-inspect: ## Inspect buildx configuration
	@docker buildx inspect $(REMOTE_BUILD_KIT_NAME)

.PHONY: docker-gen-info docker-info docker-install docker-inspect