# DO NOT EDIT THIS FILE
# DO NOT EDIT THIS FILE
# DO NOT EDIT THIS FILE
# DO NOT EDIT THIS FILE
# Generated code
# DO NOT EDIT THIS FILE
# DO NOT EDIT THIS FILE
# DO NOT EDIT THIS FILE
# DO NOT EDIT THIS FILE

# Docker Bake module for projects using docker-bake.hcl
# This module requires Makefile.docker-common.mk to be included first

# Bake-specific settings
DOCKER_BAKE_FILE ?= docker-bake.hcl
DOCKER_BAKE_TARGET ?=          # Specific target(s) to build
DOCKER_BAKE_GROUP ?= default   # Group to build when no target specified
DOCKER_BAKE_PRINT ?=           # Set to 1 to only print config

# Check if docker-bake.hcl exists
HAS_BAKE_FILE := $(shell test -f $(DOCKER_BAKE_FILE) && echo "YES" || echo "NO")

# Push/load settings for bake
DOCKER_PUSH_ARGS_BAKE := --set "*.output=type=registry,push=true"
DOCKER_LOAD_ARGS_BAKE := --set "*.output=type=docker"

# Bake build function
define docker_bake
	@echo "🔨 Building with Docker Bake..."
	@echo "📋 Bake file: $(DOCKER_BAKE_FILE)"
	@if [ -n "$(DOCKER_BAKE_TARGET)" ]; then \
		echo "🎯 Target(s): $(DOCKER_BAKE_TARGET)"; \
	else \
		echo "🎯 Group: $(DOCKER_BAKE_GROUP)"; \
	fi
	@echo "🎯 Target platforms: $(PLATFORMS)"
	@echo "🏷️  Extra tags: $(IMAGE_TAGS)"
	@if [ -n "$(REMOTE_BUILD_KIT)" ]; then \
		echo "🌐 Using remote builder: $(REMOTE_BUILD_KIT_NAME)"; \
	else \
		echo "💻 Building locally"; \
	fi
	@echo "🚀 Starting bake build..."

	GIT_BRANCH="$(GIT_BRANCH)" \
	EXTRA_TAGS="$(IMAGE_TAGS)" \
	BUILD_DATE="$(BUILD_DATE)" \
	PLATFORMS="$(PLATFORMS)" \
	docker buildx bake \
		$(if $(REMOTE_BUILD_KIT),--builder $(REMOTE_BUILD_KIT_NAME),) \
		--progress=$(DOCKER_BUILD_PROGRESS) \
		$(if $(DOCKER_BAKE_PRINT),--print,) \
		$(1) \
		-f $(DOCKER_BAKE_FILE) \
		-f $(MAKEFILES_DIR)/docker-common.hcl \
		$(if $(DOCKER_BAKE_TARGET),$(DOCKER_BAKE_TARGET),$(DOCKER_BAKE_GROUP))
endef

## Docker Bake Commands
docker-bake-build: docker-gen-info docker-install ## Build with docker-bake.hcl
ifeq ($(HAS_BAKE_FILE),NO)
	@echo "❌ Error: $(DOCKER_BAKE_FILE) not found"
	@exit 1
else
	$(call docker_bake)
endif

# Build and push with bake
docker-bake-push: docker-gen-info docker-install ## Build and push with docker-bake.hcl
ifeq ($(HAS_BAKE_FILE),NO)
	@echo "❌ Error: $(DOCKER_BAKE_FILE) not found"
	@exit 1
else
	$(call docker_bake,$(DOCKER_PUSH_ARGS_BAKE))
endif

# Build and load locally with bake
docker-bake-load: docker-gen-info docker-install ## Build and load locally with docker-bake.hcl
ifeq ($(HAS_BAKE_FILE),NO)
	@echo "❌ Error: $(DOCKER_BAKE_FILE) not found"
	@exit 1
else
	$(call docker_bake,$(DOCKER_LOAD_ARGS_BAKE))
endif

# Print bake configuration
docker-bake-print: ## Print bake configuration
ifeq ($(HAS_BAKE_FILE),NO)
	@echo "❌ Error: $(DOCKER_BAKE_FILE) not found"
	@exit 1
else
	@$(MAKE) docker-bake-build DOCKER_BAKE_PRINT=1
endif

# List available bake targets
docker-bake-targets: ## List available bake targets
ifeq ($(HAS_BAKE_FILE),NO)
	@echo "❌ Error: $(DOCKER_BAKE_FILE) not found"
	@exit 1
else
	@echo "📑 Available bake targets:"
	@docker buildx bake -f $(DOCKER_BAKE_FILE) --print 2>/dev/null | \
		jq -r '.target | keys[]' | sort | sed 's/^/  - /' || \
		echo "Error: Unable to parse bake file"
endif

# List available bake groups
docker-bake-groups: ## List available bake groups
ifeq ($(HAS_BAKE_FILE),NO)
	@echo "❌ Error: $(DOCKER_BAKE_FILE) not found"
	@exit 1
else
	@echo "👥 Available bake groups:"
	@docker buildx bake -f $(DOCKER_BAKE_FILE) --print 2>/dev/null | \
		jq -r '.group | keys[]' | sort | sed 's/^/  - /' || \
		echo "Error: Unable to parse bake file"
endif

# Aliases for common use cases
docker-bake: docker-bake-build ## Alias for docker-bake-build

.PHONY: docker-bake-build docker-bake-push docker-bake-load docker-bake-print docker-bake-targets docker-bake-groups docker-bake