# DO NOT EDIT THIS FILE
# DO NOT EDIT THIS FILE
# DO NOT EDIT THIS FILE
# DO NOT EDIT THIS FILE
# Generated code
# DO NOT EDIT THIS FILE
# DO NOT EDIT THIS FILE
# DO NOT EDIT THIS FILE
# DO NOT EDIT THIS FILE

# Legacy Docker module for single Dockerfile projects
# This module requires Makefile.docker-common.mk to be included first

# Image naming
DOCKER_IMAGE_NAME ?= zondax/unknown

# Default to empty (builds final stage), can be overridden with a specific stage name
DOCKER_BUILD_TARGET ?=

# Base image name without target prefix - generated from tags list
BASE_IMAGE_NAMES = $(foreach tag,$(IMAGE_TAGS),$(DOCKER_IMAGE_NAME):$(tag))

# Final image names - add target prefix if DOCKER_BUILD_TARGET is set
IMAGE_NAMES = $(if $(DOCKER_BUILD_TARGET),\
	$(foreach name,$(BASE_IMAGE_NAMES),$(subst :,:$(DOCKER_BUILD_TARGET)-,$(name))),\
	$(BASE_IMAGE_NAMES))

# Legacy docker build function
define docker_legacy
	@echo "🔨 Building Docker image..."
	@echo "🎯 Target platforms: $(PLATFORMS)"
	@if [ -n "$(DOCKER_BUILD_TARGET)" ]; then \
		echo "🎯 Building target stage: $(DOCKER_BUILD_TARGET)"; \
	fi
	@echo "🔧 Build args:"
	@echo "📦 Image tags:"
	@for tag in $(IMAGE_NAMES); do echo "   $$tag"; done
	@if [ -n "$(REMOTE_BUILD_KIT)" ]; then \
		echo "🌐 Using remote builder: $(REMOTE_BUILD_KIT_NAME)"; \
	else \
		echo "💻 Building locally"; \
	fi
	@echo "🚀 Starting build..."

	docker buildx build \
		--platform $(PLATFORMS) \
		$(if $(REMOTE_BUILD_KIT),--builder $(REMOTE_BUILD_KIT_NAME),) \
		--progress=$(DOCKER_BUILD_PROGRESS) \
		$(if $(DOCKER_BUILD_TARGET),--target $(DOCKER_BUILD_TARGET),) \
		$(foreach tag,$(IMAGE_NAMES),-t $(tag)) \
		$(1) .
endef

## Docker Legacy Commands
docker-build: docker-gen-info docker-install ## Build multi-platform Docker images
	$(call docker_legacy)

# Build and load Docker images locally
docker-load: docker-gen-info docker-install ## Build and load Docker images locally
	$(call docker_legacy,--load)

# Build and publish Docker images to registry
docker-publish: docker-gen-info docker-install ## Build and publish to registry
	@echo "🔄 Using builder: $(REMOTE_BUILD_KIT_NAME)"
	@echo "🎯 Publishing to platforms: $(PLATFORMS)"
	@echo "📦 Publishing images:"
	@for tag in $(IMAGE_NAMES); do echo "   $$tag"; done
	@echo "🚀 Starting build and push..."
	$(call docker_legacy,--push --output type=registry,registry.addr=docker.io)

docker-targets: ## Show available build targets from Dockerfile
	@echo "📑 Available build targets:"
	@grep "^FROM .* AS " Dockerfile | sed 's/FROM .* AS \(.*\)/  - \1/'
	@echo "  - <final stage> (default)"
	@echo
	@echo "You can set the DOCKER_BUILD_TARGET environment variable to build a specific target."

docker-bash: ## (obsolete?) Start container with bash shell, requires $APP_NAME
	docker run --platform linux/amd64 -it zondax/${APP_NAME}:latest /bin/sh

.PHONY: docker-build docker-load docker-publish docker-targets docker-bash